sonata_admin:
    title: 'Admin'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }

    options:
        legacy_twig_text_extension: false
        use_select2:    true


    security:
        handler: sonata.admin.security.handler.role

        role_admin: ROLE_ADMIN
        role_super_admin: ROLE_SUPER_ADMIN

    templates:
        layout:  'admin_standard_layout.html.twig'

    search: false

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
