twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - '@SonataForm/Form/datepicker.html.twig'
        - '@CoreUser/Form/fields.html.twig'
        - '@CoreUtility/Form/form_admin_fields.html.twig'
        - '@CoreChunkUpload/Form/fields.html.twig'
