admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

#workaround for LoginAction
sonata_user_admin_resetting_request:
    path: '/admin/password-reset'
    controller: Sonata\UserBundle\Action\LoginAction

#core_sonata_admin:
#    resource: '@CoreSonataAdminBundle/Resources/config/routing.yml'
#    prefix: admin/core

sonata_user_admin_security:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin
